# Various ways to read sattelite raster images 

### Rasterio

In [1]:
#importing rasterio Library, we are using dataset from 
import rasterio as rio

In [5]:
#open the file from the file location
src=rio.open("IL.2001155.Powell.20220871535-sur_refl_b01_1.tif")

In [6]:
#using read command we can convert the file to an array
src.read()

array([[[1547, 1474, 1474, ..., 3151, 3151, 3087],
        [1395, 1395, 1379, ..., 3323, 3323, 3148],
        [1408, 1403, 1379, ..., 3223, 3223, 3203],
        ...,
        [2196, 2186, 2255, ..., 2193, 2253, 2230],
        [2186, 2255, 2341, ..., 2154, 2235, 2217],
        [2320, 2439, 2169, ..., 2358, 2425, 2402]]], dtype=int16)

In [9]:
# to get CRS info we can use this command
src.crs

CRS.from_wkt('PROJCS["unnamed",GEOGCS["Unknown datum based upon the custom spheroid",DATUM["Not_specified_based_on_custom_spheroid",SPHEROID["Custom spheroid",6371007.181,0]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]],PROJECTION["Sinusoidal"],PARAMETER["longitude_of_center",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]')

### Gdal


In [11]:
# to laod file using Gdal
from osgeo import gdal

In [13]:
src=gdal.Open("IL.2001155.Powell.20220871535-sur_refl_b01_1.tif")

In [14]:
src.ReadAsArray()

array([[1547, 1474, 1474, ..., 3151, 3151, 3087],
       [1395, 1395, 1379, ..., 3323, 3323, 3148],
       [1408, 1403, 1379, ..., 3223, 3223, 3203],
       ...,
       [2196, 2186, 2255, ..., 2193, 2253, 2230],
       [2186, 2255, 2341, ..., 2154, 2235, 2217],
       [2320, 2439, 2169, ..., 2358, 2425, 2402]], dtype=int16)

In [17]:
#getting projection info in Gdal
src.GetProjection()

'PROJCS["unnamed",GEOGCS["Unknown datum based upon the custom spheroid",DATUM["Not_specified_based_on_custom_spheroid",SPHEROID["Custom spheroid",6371007.181,0]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]],PROJECTION["Sinusoidal"],PARAMETER["longitude_of_center",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]'

### openCV

In [19]:
# loading file using openCV
import cv2

In [23]:
#we have to laod usinf cv2.IMREAD_LOAD_GDAL
cv2.imread("IL.2001155.Powell.20220871535-sur_refl_b01_1.tif", cv2.IMREAD_LOAD_GDAL)

array([[1547, 1474, 1474, ..., 3151, 3151, 3087],
       [1395, 1395, 1379, ..., 3323, 3323, 3148],
       [1408, 1403, 1379, ..., 3223, 3223, 3203],
       ...,
       [2196, 2186, 2255, ..., 2193, 2253, 2230],
       [2186, 2255, 2341, ..., 2154, 2235, 2217],
       [2320, 2439, 2169, ..., 2358, 2425, 2402]], dtype=uint16)

### PIL

In [28]:
from PIL import Image
import numpy as np

In [27]:
src=Image.open("IL.2001155.Powell.20220871535-sur_refl_b01_1.tif")

In [30]:
# using numpy to covert it to an array
np.array(src)

array([[1547, 1474, 1474, ..., 3151, 3151, 3087],
       [1395, 1395, 1379, ..., 3323, 3323, 3148],
       [1408, 1403, 1379, ..., 3223, 3223, 3203],
       ...,
       [2196, 2186, 2255, ..., 2193, 2253, 2230],
       [2186, 2255, 2341, ..., 2154, 2235, 2217],
       [2320, 2439, 2169, ..., 2358, 2425, 2402]])